### 

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "firstName": "Yoo",
  "lastName": "WHT",
  "password": "testpassword"
}


### 

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "demo.customer@eshop.local",
  "password": "123456"
}


### 

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}


### 

GET http://localhost:8080/api/auth/me HTTP/1.1
Authorization: Bearer {{profileAccessToken}}


### 

GET http://localhost:8080/api/auth/test-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0b2tlblR5cGUiOiJBQ0NFU1MiLCJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc1ODI4NzM1MywiZXhwIjoxNzU4MjkwOTUzfQ.waw_6bj2nXgv1utaEvQ-P0LWykwEmFstSq5vVwHDa5I


### 

POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0b2tlblR5cGUiOiJSRUZSRVNIIiwic3ViIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NTgyODYwMTUsImV4cCI6MTc1OTU4MjAxNX0.Aj98PI7eUaRIXCny4diVB5gwg4hRnAEdYes_yLZMp6w"
}


### 

GET http://localhost:8080/actuator/health HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0b2tlblR5cGUiOiJBQ0NFU1MiLCJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc1ODI5Njg1NiwiZXhwIjoxNzU4MzAwNDU2fQ.slJmDwZHJ1th4LpBoMEXkOJDK_vPl44E7tF3n0RIHSw


### 

GET http://localhost:8080/api/auth/activate?token=26440601-48de-4ae0-9620-830507527eee HTTP/1.1


### 

POST http://localhost:8080/api/auth/activate/resend HTTP/1.1
Content-Type: application/json

{
  "email": "huynhminhthinh003@gmail.com"
}


### 

@profileAccessToken = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0b2tlblR5cGUiOiJBQ0NFU1MiLCJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc2MjI3NDk3NiwiZXhwIjoxNzYyNjM0OTc2fQ.XYgGFdMBBU_CmS78B-lRtfDL_6eL7txS7119irnnsok


### Get current profile

GET http://localhost:8080/api/account/profile HTTP/1.1
Authorization: Bearer {{profileAccessToken}}


### Update profile

PUT http://localhost:8080/api/account/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{profileAccessToken}}

{
  "firstName": "Jane",
  "lastName": "Doe",
  "phone": "+1 555 000 1234"
}


### Change password

PATCH http://localhost:8080/api/account/profile/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{profileAccessToken}}

{
  "confirmPassword": "testpassword",
  "currentPassword": "newSecret123",
  "newPassword": "testpassword"
}


### Request password reset (public)

POST http://localhost:8080/api/auth/password/reset/request HTTP/1.1
Content-Type: application/json

{
  "email": "vuadeptraitg@gmail.com"
}


### Confirm password reset (public)

POST http://localhost:8080/api/auth/password/reset/confirm HTTP/1.1
Content-Type: application/json

{
  "confirmPassword": "brandNew123",
  "email": "test@gmail.com",
  "newPassword": "brandNew123",
  "token": "1234"
}
